server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://192.168.138.136:3306/dbecom?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true