server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/dbecom?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: steven720